spring.application.name=firstApp
spring.datasource.url=jdbc:mysql://localhost:3306/springbootproject
spring.datasource.username=root
spring.datasource.password=Feedmemore123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=heythere
jwt.expiration=86400000
spring.main.allow-circular-references=true